#!/usr/bin/env python3
"""WP13 - Compact stacking model under grouped, leakage-resistant cross-validation.

Reviewer 1 comment 3 flags gene-identity carryover in edge-level CV. WP1 applied
grouped CV to the geometry bundle; this script extends the same stress test to
the COMPACT stacking model that combines scGPT and Geneformer branches.

For each domain and each CV scheme (edge-level vs leave-both-out) we evaluate:
  * baseline                 - six confound features
  * baseline + scGPT bundle
  * baseline + Geneformer bundle
  * compact (stacked)        - meta-LR on baseline + out-of-fold branch probs
The compact model uses nested cross-validation: branch out-of-fold predictions
are generated by inner stratified CV within each outer training fold.

Output: implementation/outputs/cycle53_compact_grouped/compact_grouped_summary.csv
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold

import revision_lib as rl
from run_wp6_eval_cross_model import load_geneformer_domain


def branch_oof_and_test(feat, y, tr, te, inner_k=4, seed=0):
    """Out-of-fold predictions on `tr` plus predictions on `te` for one branch."""
    oof_tr = np.zeros(len(tr))
    skf = StratifiedKFold(n_splits=inner_k, shuffle=True, random_state=seed)
    for itr, ite in skf.split(np.zeros(len(tr)), y[tr]):
        if len(np.unique(y[tr][itr])) < 2:
            continue
        oof_tr[ite] = rl._fit_predict(feat[tr][itr], y[tr][itr], feat[tr][ite])
    test_pred = rl._fit_predict(feat[tr], y[tr], feat[te])
    return oof_tr, test_pred


def main() -> None:
    OUT = rl.OUTPUTS / "cycle53_compact_grouped"
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for domain in rl.DOMAINS:
        scg = rl.load_domain(domain, 42)
        gf = load_geneformer_domain(domain)
        layers_s = list(range(scg.n_layers))
        layers_g = list(range(gf.n_layers))
        geom_s = rl.geom_feature_matrix(scg, "centered_cosine", layers_s)
        geom_g = rl.geom_feature_matrix(gf, "centered_cosine", layers_g)
        m = (rl.valid_mask(scg, layers_s, geom_s) &
             rl.valid_mask(gf, layers_g, geom_g))
        y = scg.labels[m].astype(int)
        base = scg.baseline[m]
        fs = np.column_stack([base, geom_s[m]])
        fg = np.column_stack([base, geom_g[m]])
        tf = scg.edges["source"].to_numpy()[m]
        tg = scg.edges["target"].to_numpy()[m]

        for cv_mode in ("edge", "leave_both"):
            if cv_mode == "edge":
                splits = rl.edge_cv_splits(y, seed=42)
            else:
                splits = rl.leave_both_out_splits(tf, tg, seed=42)
                used = np.unique(np.concatenate(
                    [np.concatenate([tr, te]) for tr, te in splits]))
                remap = {o: i for i, o in enumerate(used)}
                yy = y[used]; bb = base[used]; ss = fs[used]; gg = fg[used]
                splits = [(np.array([remap[i] for i in tr]),
                           np.array([remap[i] for i in te])) for tr, te in splits]
            if cv_mode == "edge":
                yy, bb, ss, gg = y, base, fs, fg

            base_oof = rl.cv_oof_probs(bb, yy, splits)
            scg_oof = rl.cv_oof_probs(ss, yy, splits)
            gf_oof = rl.cv_oof_probs(gg, yy, splits)
            # compact stacked model
            comp_oof = np.zeros(len(yy)); cnt = np.zeros(len(yy))
            for tr, te in splits:
                if len(np.unique(yy[tr])) < 2:
                    continue
                a_tr, a_te = branch_oof_and_test(ss, yy, tr, te)
                b_tr, b_te = branch_oof_and_test(gg, yy, tr, te)
                meta_tr = np.column_stack([bb[tr], a_tr, b_tr])
                meta_te = np.column_stack([bb[te], a_te, b_te])
                comp_oof[te] += rl._fit_predict(meta_tr, yy[tr], meta_te)
                cnt[te] += 1
            comp_oof /= np.where(cnt > 0, cnt, 1)

            au = {n: rl.safe_auroc(yy, p) for n, p in
                  [("baseline", base_oof), ("scGPT", scg_oof),
                   ("Geneformer", gf_oof), ("compact", comp_oof)]}
            best_single = max(au["scGPT"], au["Geneformer"])
            bs = rl.bootstrap_delta(yy, np.where(au["scGPT"] >= au["Geneformer"],
                                                 scg_oof, gf_oof),
                                    comp_oof, n_iters=1000, seed=6)
            row = dict(domain=domain, cv_mode=cv_mode, n_edges=int(len(yy)),
                       auroc_baseline=au["baseline"], auroc_scGPT=au["scGPT"],
                       auroc_Geneformer=au["Geneformer"], auroc_compact=au["compact"],
                       delta_compact_vs_best=au["compact"] - best_single,
                       boot_delta_lo=bs["delta_lo"], boot_delta_hi=bs["delta_hi"],
                       ci_excludes_zero=bool(bs["delta_lo"] > 0))
            rows.append(row)
            print(f"[{domain:13s} {cv_mode:11s}] base={au['baseline']:.3f} "
                  f"scGPT={au['scGPT']:.3f} GF={au['Geneformer']:.3f} "
                  f"compact={au['compact']:.3f} "
                  f"d(compact-best)={row['delta_compact_vs_best']:+.4f}")
    pd.DataFrame(rows).to_csv(OUT / "compact_grouped_summary.csv", index=False)
    print(f"\n[done] {OUT / 'compact_grouped_summary.csv'}")


if __name__ == "__main__":
    main()
