name: subproject38-geo-v2
channels:
  - pytorch
  - conda-forge
dependencies:
  - anndata=0.12.6
  - h5py
  - ipython
  - matplotlib=3.9
  - numpy=1.26
  - pandas=2.2
  - python=3.11
  - pytorch=2.2
  - pyyaml
  - scikit-learn=1.5
  - scipy=1.13
  - tqdm
